// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcutbwudqqpmdvthbalj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjdXRid3VkcXFwbWR2dGhiYWxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTIxODgsImV4cCI6MjA2MzQyODE4OH0.ZUDJCWXJ7iJWPC8MjswojxUH1xjvSltGbqT5tzh_Bmw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);